name: Playwright Tests (Chromium + Allure)

on:
  push:
    branches: [ main, develop,]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Clean previous build
        run: |
          echo "Cleaning previous build, node_modules and reports..."
          rm -rf node_modules
          rm -rf playwright-report
          rm -rf allure-report
          rm -rf allure-results
          npm cache clean --force

      # Step 3: Create .env file from GitHub Secrets
      # (All sensitive values are stored in Settings → Secrets and variables → Actions)
      - name: Create .env from GitHub Secrets
        run: |
          echo "CHEMVERIC_UI_URL=${{ secrets.CHEMVERIC_UI_URL }}" >> .env
          echo "CHEMVERIC_API_URL=${{ secrets.CHEMVERIC_API_URL }}" >> .env
          echo "CHEMVERIC_ADMIN_EMAIL=${{ secrets.CHEMVERIC_ADMIN_EMAIL }}" >> .env
          echo "CHEMVERIC_ADMIN_PASSWORD=${{ secrets.CHEMVERIC_ADMIN_PASSWORD }}" >> .env
          echo "INVITE_BUYER_EMAIL=${{ secrets.INVITE_BUYER_EMAIL }}" >> .env
          echo "INVITE_VENDOR_EMAIL=${{ secrets.INVITE_VENDOR_EMAIL }}" >> .env
          echo "HEADLESS=true" >> .env
          cat .env

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm ci || npm install

      # Step 5: Install Chromium for Playwright
      - name: Prepare Playwright Chromium
        run: npm run prepare

      # Step 6: Run Playwright tests (Chromium only)
      - name: Run Playwright tests (Chromium only)
        run: npx playwright test --project=Chromium
      
       # Step : Install Allure CLI  
      - name: Install Allure CLI
        run: npm install -g allure-commandline --save-dev  

      # Step 7: Always generate Allure report even if tests failed
      - name: Always generate Allure report
        if: always()
        run: |
          npx allure generate --clean -o ./allure-report ./allure-results || true

      # Step 8: Upload Playwright HTML report (always)
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      # Step 9: Upload Allure HTML report (always)
      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
